//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestionnaireReport
    {
        public int report_id { get; set; }
        public string report_file_path { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public Nullable<int> userId { get; set; }
        public string comment { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> case_id { get; set; }
        public string report_description { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual AlertRequest AlertRequestNew { get; set; }
    }
}
