//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriqueProcess
    {
        public int historique_id { get; set; }
        public Nullable<int> userId { get; set; }
        public string actions { get; set; }
        public string comment { get; set; }
        public string status { get; set; }
        public Nullable<int> case_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> saisie_operation_header_id { get; set; }
    
        public virtual Workflow Workflow { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual SaisieOperationHeader SaisieOperationHeader { get; set; }
    }
}
