//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int operation_id { get; set; }
        public Nullable<int> type_operation_id { get; set; }
        public string operation_description { get; set; }
        public string account_debit { get; set; }
        public string account_credit { get; set; }
        public string amount { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual TypeOperation TypeOperation { get; set; }
    }
}
