//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherCustomerSaisie
    {
        public int other_customer_saisie_id { get; set; }
        public string creancier_saisissant { get; set; }
        public string debiteur_saisie { get; set; }
        public string montant_poursuivi { get; set; }
        public string numero_compte { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> search_by { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
