//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process
    {
        public int processId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> isCompleted { get; set; }
        public Nullable<int> initiated_by { get; set; }
        public Nullable<int> decision_id { get; set; }
        public Nullable<int> next_user_status { get; set; }
        public Nullable<int> case_id { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> seq_no { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> stepId { get; set; }
        public string reject_comment { get; set; }
        public string approve_comment { get; set; }
    
        public virtual Step Step { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
        public virtual Workflow Workflow { get; set; }
        public virtual Role Role { get; set; }
    }
}
