//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_submenu
    {
        public int idrole_menu { get; set; }
        public int idroles { get; set; }
        public int idsubmenu { get; set; }
    
        public virtual submenu submenu { get; set; }
        public virtual Role Role { get; set; }
    }
}
