//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaisieOperationHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaisieOperationHeader()
        {
            this.HistoriqueProcesses = new HashSet<HistoriqueProcess>();
            this.SaisieOperations = new HashSet<SaisieOperation>();
        }
    
        public int saisie_operation_header_id { get; set; }
        public string account_no { get; set; }
        public string account_name { get; set; }
        public Nullable<System.DateTime> date_saisie { get; set; }
        public Nullable<int> statut { get; set; }
        public string amount { get; set; }
        public Nullable<int> saved_by { get; set; }
        public string document_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriqueProcess> HistoriqueProcesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaisieOperation> SaisieOperations { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
