//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaisieOperation
    {
        public int saisie_operation_id { get; set; }
        public string branch_code { get; set; }
        public string account_no { get; set; }
        public string account_name { get; set; }
        public string operation_description { get; set; }
        public string amount_debit { get; set; }
        public string amount_credit { get; set; }
        public Nullable<int> saisie_type_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> saisie_operation_header_id { get; set; }
    
        public virtual SaisieOperationHeader SaisieOperationHeader { get; set; }
        public virtual SaisieType SaisieType { get; set; }
    }
}
