//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketAssignment
    {
        public int ticket_assignment_id { get; set; }
        public Nullable<int> ticket_id { get; set; }
        public Nullable<int> staff_id { get; set; }
        public Nullable<System.DateTime> assigned_at { get; set; }
        public Nullable<System.DateTime> completed_at { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
